#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#picom experimental
picom &> /dev/null &

#load theme.toml
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#background 
nitrogen --set-zoom-fill $SCRIPTPATH/background.jpg
#nitrogen --restore 

ntfd &
#polybar -c $SCRIPTPATH/polybar.config main &> /dev/null &
$SCRIPTPATH/polybar/polylaunch

#autostart
dunst &
#lxpolkit &
volctl &
caffeine &
nm-applet &
pamac-tray &
blueman-applet 
