#!/usr/bin/sh
pkill polybar

polybar -c ~/.config/leftwm/themes/current/polybar/polybar.config main 2>&1 | tee -a /tmp/polybar.log &disown
polybar -c ~/.config/leftwm/themes/current/polybar/polybar.config secondary 2>&1 | tee -a /tmp/polybar.log &disown
