#!/usr/bin/sh
pkill polybar

polybar -c ~/.config/leftwm/themes/current/polybar/polybar.config standalone 2>&1 | tee -a /tmp/polybar.log &disown
#polybar -c ~/.config/leftwm/themes/current/polybar/polybar.config bottom 2>&1 | tee -a /tmp/polybar.log &disown
